---
abstract: 'Fast XS implementation of MaxMind DB reader'
author:
  - 'Boris Zentner <bzentner@maxmind.com>'
  - 'Dave Rolsky <drolsky@maxmind.com>'
  - 'Ran Eilam <reilam@maxmind.com>'
build_requires:
  Module::Build: 0.3601
  Net::Works::Network: 0
  Test::Fatal: 0
  Test::MaxMind::DB::Common::Util: 0
  Test::More: 0
  Test::Number::Delta: 0
  autodie: 0
  lib: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MaxMind-DB-Reader-XS
no_index:
  file:
    - t/lib/Test/MaxMind/DB/Reader.pm
requires:
  Math::Int128: 0
  MaxMind::DB::Metadata: 0
  MaxMind::DB::Reader: 0.050002
  MaxMind::DB::Reader::Role::HasMetadata: 0
  MaxMind::DB::Reader::Role::Reader: 0
  MaxMind::DB::Types: 0
  Moo: 0
  XSLoader: 0
  namespace::autoclean: 0
  perl: 5.010000
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/maxmind/MaxMind-DB-Reader-XS/issues
  repository: git://github.com/maxmind/MaxMind-DB-Reader-XS.git
version: 0.060004
x_authority: cpan:TJMATHER
x_contributors:
  - 'Greg Oschwald <goschwald@maxmind.com>'
  - 'Olaf Alders <oalders@maxmind.com>'
